os: linux
dist: focal
language: php

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

jobs:
    include:
        -
            stage: test
            env:
                - COMPOSER_VERSION=2
            install:
                - composer install --no-interaction
            script:
                - vendor/bin/grumphp run

        -
            stage: prod
            env:
                - COMPOSER_VERSION=2 APP_ENV=prod
            install:
                - composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction
                - composer dump-autoload --classmap-authoritative --no-dev
                - composer run-script --no-dev post-install-cmd
            before_deploy:
                - git config --local user.name "$GIT_USER"
                - git config --local user.email "$GIT_EMAIL"
                - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
                - git tag $TRAVIS_TAG
            deploy:
                provider: releases
                edge: true
                token: $GITHUB_TOKEN
                cleanup: false
