os: linux
dist: focal
language: php

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

jobs:
    include:
        -
            stage: test
            env:
                - COMPOSER_VERSION=2
            install:
                - composer install --no-interaction
            script:
                - vendor/bin/grumphp run

        -
            stage: prod
            if: tag IS present
            env:
                - COMPOSER_VERSION=2 APP_ENV=prod
            install:
                - composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction
                - composer dump-autoload --classmap-authoritative --no-dev
                - composer run-script --no-dev post-install-cmd
            before_deploy:
                - rm composer.lock grumphp.yml phpcs.xml.dist phpstan.neon phpunit.xml.dist symfony.lock
                - rm -rf ./var
                - mkdir -p ./var/cache ./var/log
                - zip -rq9 webhooks-$TRAVIS_TAG.zip ./*
            deploy:
                provider: releases
                edge: true
                file: webhooks-$TRAVIS_TAG.zip
                token: $GITHUB_TOKEN
                cleanup: false
                on:
                    tags: true

        -
            stage: release-candidate
            if: branch =~ /^release\/.*$/
            env:
                - COMPOSER_VERSION=2 APP_ENV=prod
            install:
                - composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction
                - composer dump-autoload --classmap-authoritative --no-dev
                - composer run-script --no-dev post-install-cmd
            before_deploy:
                - rm composer.lock grumphp.yml phpcs.xml.dist phpstan.neon phpunit.xml.dist symfony.lock
                - rm -rf ./var
                - mkdir -p ./var/cache ./var/log
                - export RELEASE_NAME=`echo "$TRAVIS_BRANCH" | sed 's@release/\(.*\)@\1@'`
                - zip -rq9 webhooks-${RELEASE_NAME}-RC${TRAVIS_BUILD_ID}.zip ./*
            deploy:
                provider: releases
                edge: true
                file: webhooks-${RELEASE_NAME}-RC${TRAVIS_BUILD_ID}.zip
                token: $GITHUB_TOKEN
                cleanup: false
