version: "3.8"

services:
    nginx:
        container_name: ${APP_NAME:-webhooks}_nginx
        image: nginx:alpine
        ports:
            - 80:80
        restart: always
        working_dir: /srv/app/
        volumes:
            - ./:/srv/app/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        container_name: ${APP_NAME:-webhooks}_php
        image: numberninecms/php:7.4-fpm
        working_dir: /srv/app/
        user: '1000'
        restart: always
        env_file:
            - .env.local
        volumes:
            - ./:/srv/app/
